version: '3.8'

networks:
  web:
    external: true
    driver: bridge

services:
  db:
    image: postgres:13.5
    container_name: niyo-planner-db
    restart: always
    environment:
      - POSTGRES_USER=${PSQL_USERNAME}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5444:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  redis:
    image: redis:latest
    container_name: niyo-planner-cache
    ports:
      - '6389:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres:
