version: '3.8'

networks:
  web:
    external: true
    driver: bridge

services:
  server:
    platform: linux/arm64
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: niyo-planner-server
    volumes:
      - .:/app
    ports:
      - '8001:3000'
    env_file:
      - ./.env
    environment:
      REDIS_URI: redis://redis:6379/0
      DATABASE_URL: 'postgres://${PSQL_USERNAME}:${PSQL_PASSWORD}@db:5432/niyo-planner'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:13.5
    container_name: niyo-planner-db
    restart: always
    environment:
      - POSTGRES_USER=${PSQL_USERNAME}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5444:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  redis:
    image: redis:latest
    container_name: niyo-planner-cache
    ports:
      - '6389:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres:
